# Generated by Django 6.0.5 on 2026-05-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jogadores/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C')], default='C', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('jogos_historicos', models.IntegerField(default=0)),
                ('vitorias_historicas', models.IntegerField(default=0)),
                ('derrotas_historicas', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
