# Generated by Django 6.0.5 on 2026-05-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_torneio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C')], max_length=1)),
                ('quantidade_jogadores', models.IntegerField(default=20)),
                ('classificados_finais', models.IntegerField(default=8)),
                ('promovidos', models.IntegerField(default=0)),
                ('rebaixados', models.IntegerField(default=0)),
                ('melhores_resultados', models.IntegerField(default=10)),
                ('max_jogos_por_rodada', models.IntegerField(default=2)),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.torneio')),
            ],
        ),
    ]
