# Generated by Django 6.0.5 on 2026-05-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoriatorneio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriatorneio')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneio')),
            ],
        ),
    ]
