# Generated by Django 6.0.5 on 2026-05-10 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inscricaotorneio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jogo', models.CharField(choices=[('CHAMPIONSHIP_DUPLAS', 'Championship Duplas'), ('AMISTOSO_DUPLAS', 'Amistoso Duplas'), ('SIMPLES', 'Simples')], max_length=30)),
                ('rodada', models.IntegerField(blank=True, null=True)),
                ('data_jogo', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriatorneio')),
                ('torneio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.torneio')),
            ],
        ),
    ]
