# Generated by Django 6.0.5 on 2026-05-10 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('A', 'Lado A'), ('B', 'Lado B')], max_length=1)),
                ('vencedor', models.BooleanField(default=False)),
                ('pontos_ranking', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.jogo')),
            ],
        ),
    ]
