# Generated by Django 6.0.5 on 2026-05-10 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participantejogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_set', models.IntegerField()),
                ('games_lado_a', models.IntegerField()),
                ('games_lado_b', models.IntegerField()),
                ('teve_tiebreak', models.BooleanField(default=False)),
                ('tiebreak_lado_a', models.IntegerField(blank=True, null=True)),
                ('tiebreak_lado_b', models.IntegerField(blank=True, null=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.jogo')),
            ],
        ),
    ]
