# Generated by Django 6.0.5 on 2026-05-10 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_setjogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('games_feitos', models.IntegerField(default=0)),
                ('games_sofridos', models.IntegerField(default=0)),
                ('aproveitamento', models.FloatField(default=0)),
                ('posicao', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriatorneio')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneio')),
            ],
            options={
                'unique_together': {('torneio', 'categoria', 'jogador')},
            },
        ),
    ]
