# Generated by Django 6.0.5 on 2026-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rankingjogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingjogador',
            name='status_ranking',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
