# Generated by Django 6.0.5 on 2026-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jogador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CONTESTADO', 'Contestado')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='torneio',
            name='disputa',
            field=models.CharField(choices=[('SIMPLES', 'Simples'), ('DUPLAS', 'Duplas')], default='DUPLAS', max_length=20),
        ),
        migrations.AddField(
            model_name='torneio',
            name='tipo',
            field=models.CharField(choices=[('RANKING', 'Ranking'), ('MATA_MATA', 'Mata-mata'), ('GRUPOS', 'Grupos')], default='RANKING', max_length=20),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='ano',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='edicao',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20),
        ),
    ]
