# Generated by Django 6.0.5 on 2026-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jogo_status_torneio_disputa_torneio_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='fase',
            field=models.CharField(blank=True, choices=[('OITAVAS', 'Oitavas'), ('QUARTAS', 'Quartas'), ('SEMI', 'Semi Final'), ('FINAL', 'Final')], max_length=20, null=True),
        ),
    ]
