# Generated by Django 6.0.5 on 2026-05-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jogo_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='mao_dominante',
            field=models.CharField(blank=True, choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nivel',
            field=models.CharField(choices=[('INICIANTE', 'Iniciante'), ('INTERMEDIARIO', 'Intermediário'), ('AVANCADO', 'Avançado')], default='INICIANTE', max_length=20),
        ),
        migrations.AddField(
            model_name='jogador',
            name='raquete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
