# Generated by Django 6.0.5 on 2026-05-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jogador_cidade_jogador_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatorneio',
            name='rodadas_contabilizadas',
            field=models.IntegerField(default=10),
        ),
    ]
