# Generated by Django 6.0.5 on 2026-05-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_categoriatorneio_rodadas_contabilizadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'ordering': ['categoria', 'nome']},
        ),
        migrations.AlterField(
            model_name='jogador',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='mao_dominante',
            field=models.CharField(choices=[('DIREITA', 'Direita'), ('ESQUERDA', 'Esquerda')], default='DIREITA', max_length=20),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='tipo',
            field=models.CharField(choices=[('RANKING', 'Ranking'), ('MATA_MATA', 'Mata-mata'), ('GRUPOS', 'Grupos'), ('AMISTOSO', 'Amistoso'), ('TREINO', 'Treino')], default='RANKING', max_length=20),
        ),
    ]
