# Generated by Django 6.0.5 on 2026-05-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_jogador_options_alter_jogador_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='categoria',
            field=models.CharField(blank=True, choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('FASE_FINAIS', 'Fase finais'), ('ENCERRADO', 'Encerrado definitivamente')], default='ABERTO', max_length=20),
        ),
    ]
