# Generated by Django 6.0.5 on 2026-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_jogador_categoria_alter_torneio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampeaoTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C')], max_length=1)),
                ('edicao', models.IntegerField()),
                ('data_final', models.DateField()),
                ('campeao_1', models.CharField(max_length=100)),
                ('campeao_2', models.CharField(max_length=100)),
                ('finalista_1', models.CharField(max_length=100)),
                ('finalista_2', models.CharField(max_length=100)),
                ('placar', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categoria', '-edicao'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rankingjogador',
            unique_together=set(),
        ),
    ]
