# Generated by Django 6.0.5 on 2026-05-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_campeaotorneio_alter_rankingjogador_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='semifinal_cd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='titulos_cd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='vice_cd',
            field=models.IntegerField(default=0),
        ),
    ]
