# Generated by Django 6.0.5 on 2026-05-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jogador_semifinal_cd_jogador_titulos_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingjogador',
            name='posicao_anterior',
            field=models.IntegerField(default=0),
        ),
    ]
