# Generated by Django 6.0.5 on 2026-05-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rankingjogador_posicao_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='ano_inicio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano que começou a jogar'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='backhand',
            field=models.CharField(blank=True, choices=[('UMA_MAO', '1 mão'), ('DUAS_MAOS', '2 mãos')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='clube',
            field=models.CharField(blank=True, choices=[('TENIS_PANAMBI', 'Tênis Panambi'), ('AABB', 'AABB'), ('AFUBRA', 'Afubra'), ('OUTRO', 'Outro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='estilo_jogo',
            field=models.CharField(blank=True, choices=[('OFENSIVO', 'Ofensivo'), ('DEFENSIVO', 'Defensivo'), ('ALL_COURT', 'All Court'), ('SAQUE_VOLEIO', 'Saque e Voleio')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='frase_pessoal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='jogador_favorito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
