# Generated by Django 6.0.5 on 2026-06-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_jogador_ano_inicio_jogador_backhand_jogador_clube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('data', 'hora_inicio', 'hora_fim')},
            },
        ),
        migrations.CreateModel(
            name='ReservaQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogadores', models.TextField(help_text='Informe quem vai jogar neste horário.')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('checkin_realizado', models.BooleanField(default=False)),
                ('checkin_data_hora', models.DateTimeField(blank=True, null=True)),
                ('checkin_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('checkin_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('checkin_distancia_metros', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='core.horarioquadra')),
                ('reservado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_quadra', to='core.jogador')),
            ],
            options={
                'ordering': ['horario__data', 'horario__hora_inicio'],
            },
        ),
    ]
