# Generated by Django 6.0.5 on 2026-06-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_horarioquadra_reservaquadra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservaquadra',
            options={'ordering': ['data', 'horario__hora_inicio']},
        ),
        migrations.AddField(
            model_name='reservaquadra',
            name='data',
            field=models.DateField(default='2026-06-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaquadra',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('CHECKIN', 'Check-in realizado'), ('NO_SHOW', 'Não compareceu')], default='AGENDADA', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoHorarioQuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fim')},
            },
        ),
        migrations.AlterField(
            model_name='reservaquadra',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.configuracaohorarioquadra'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaquadra',
            unique_together={('data', 'horario')},
        ),
        migrations.DeleteModel(
            name='HorarioQuadra',
        ),
    ]
