# Generated by Django 6.0.5 on 2026-06-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_reservaquadra_options_reservaquadra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='configuracaohorarioquadra',
            options={'ordering': ['quadra', 'dia_semana', 'hora_inicio']},
        ),
        migrations.AlterUniqueTogether(
            name='configuracaohorarioquadra',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracaohorarioquadra',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.quadra'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaohorarioquadra',
            unique_together={('quadra', 'dia_semana', 'hora_inicio', 'hora_fim')},
        ),
    ]
