# Generated by Django 6.0.5 on 2026-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_quadra_alter_configuracaohorarioquadra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
