# Generated by Django 6.0.5 on 2026-06-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_torneio_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('edicao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='torneios/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='torneios/banners/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Torneio',
                'verbose_name_plural': 'Registros de Torneios',
                'ordering': ['-data_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('campeao', models.CharField(max_length=150)),
                ('vice', models.CharField(blank=True, max_length=150, null=True)),
                ('semifinalistas', models.TextField(blank=True, help_text='Informe os semifinalistas, se desejar.', null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.registrotorneio')),
            ],
            options={
                'verbose_name': 'Resultado do Torneio',
                'verbose_name_plural': 'Resultados dos Torneios',
                'ordering': ['ordem', 'categoria'],
            },
        ),
    ]
