# Generated by Django 6.0.5 on 2026-06-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_registrotorneio_resultadotorneio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotorneio',
            options={'ordering': ['-data_inicio', '-id'], 'verbose_name': 'Histórico de Torneio', 'verbose_name_plural': 'Histórico de Torneios'},
        ),
        migrations.RenameField(
            model_name='registrotorneio',
            old_name='descricao',
            new_name='observacoes',
        ),
        migrations.RemoveField(
            model_name='registrotorneio',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='resultadotorneio',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='resultadotorneio',
            name='semifinalistas',
        ),
        migrations.AddField(
            model_name='registrotorneio',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Simples'), ('DUPLAS', 'Duplas'), ('SIMPLES_DUPLAS', 'Simples e Duplas'), ('GERAL', 'Geral')], default='GERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='registrotorneio',
            name='total_categorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrotorneio',
            name='total_inscritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrotorneio',
            name='total_jogos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrotorneio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='historico_torneios/logos/'),
        ),
        migrations.AlterField(
            model_name='resultadotorneio',
            name='campeao',
            field=models.CharField(help_text='Para duplas, informe: Jogador 1 / Jogador 2', max_length=200),
        ),
        migrations.AlterField(
            model_name='resultadotorneio',
            name='vice',
            field=models.CharField(blank=True, help_text='Para duplas, informe: Jogador 1 / Jogador 2', max_length=200, null=True),
        ),
    ]
