# Generated by Django 6.0.5 on 2026-06-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_registrotorneio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem_desktop', models.ImageField(upload_to='banners/desktop/')),
                ('imagem_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('link', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner do Site',
                'verbose_name_plural': 'Banners do Site',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='jogo',
            name='tipo_jogo',
            field=models.CharField(choices=[('SIMPLES', 'Simples Amistoso'), ('AMISTOSO_DUPLAS', 'Duplas Amistoso'), ('CHAMPIONSHIP_SIMPLES', 'Championship Simples'), ('CHAMPIONSHIP_DUPLAS', 'Championship Duplas')], max_length=30),
        ),
    ]
