# Generated by Django 6.0.5 on 2026-06-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_bannersite_alter_jogo_tipo_jogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersite',
            options={'ordering': ['pagina', 'ordem', '-criado_em'], 'verbose_name': 'Banner do Site', 'verbose_name_plural': 'Banners do Site'},
        ),
        migrations.AddField(
            model_name='bannersite',
            name='cliques',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bannersite',
            name='pagina',
            field=models.CharField(choices=[('HOME', 'Home'), ('RANKING', 'Ranking'), ('TORNEIOS', 'Torneios'), ('QUADRAS', 'Quadras'), ('HEADTOHEAD', 'Head to Head')], default='HOME', max_length=30),
        ),
        migrations.AddField(
            model_name='bannersite',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/'),
        ),
        migrations.AddField(
            model_name='bannersite',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bannersite',
            name='imagem_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='banners/desktop/'),
        ),
    ]
