# Generated by Django 6.0.5 on 2026-06-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_bannersite_options_bannersite_cliques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='controle_lancamento',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('SABADO', 'Somente aos sábados'), ('MANUAL', 'Bloqueado manualmente')], default='LIVRE', max_length=20),
        ),
    ]
