# Generated by Django 6.0.5 on 2026-06-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_torneio_controle_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categorias', models.CharField(blank=True, help_text='Ex: Categoria A, Categoria B, Infantil, Feminino', max_length=200, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('data_abertura_inscricoes', models.DateField(blank=True, null=True)),
                ('data_fechamento_inscricoes', models.DateField(blank=True, null=True)),
                ('link_inscricao', models.URLField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos_calendario/')),
                ('status', models.CharField(choices=[('EM_BREVE', 'Em breve'), ('INSCRICOES_ABERTAS', 'Inscrições abertas'), ('INSCRICOES_ENCERRADAS', 'Inscrições encerradas'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='EM_BREVE', max_length=30)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_inicio', 'nome'],
            },
        ),
    ]
