# Generated by Django 6.0.5 on 2026-06-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_eventocalendario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'ordering': ['data_inicio', 'nome'], 'verbose_name': 'Evento do Calendário', 'verbose_name_plural': 'Eventos do Calendário'},
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='cor_evento',
            field=models.CharField(blank=True, help_text='Ex: azul, verde, laranja', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='limite_vagas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_calendario/logos/'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='regulamento',
            field=models.FileField(blank=True, null=True, upload_to='eventos_calendario/regulamentos/'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='tipo_evento',
            field=models.CharField(choices=[('TORNEIO', 'Torneio'), ('CLINICA', 'Clínica'), ('CURSO', 'Curso'), ('SOCIAL', 'Evento Social'), ('FESTIVAL', 'Festival'), ('OUTRO', 'Outro')], default='TORNEIO', max_length=30),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='valor_inscricao',
            field=models.CharField(blank=True, help_text='Ex: R$ 50,00 ou Gratuito', max_length=100, null=True),
        ),
    ]
