# Generated by Django 6.0.5 on 2026-06-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_eventocalendario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='logo_plataforma_inscricao',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_calendario/plataformas/'),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='plataforma_inscricao',
            field=models.CharField(blank=True, default='LetzPlay', help_text='Ex: LetzPlay', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventocalendario',
            name='link_inscricao',
            field=models.URLField(blank=True, help_text='Cole aqui o link da inscrição no LetzPlay', null=True),
        ),
    ]
