# Generated by Django 6.0.5 on 2026-06-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_eventocalendario_logo_plataforma_inscricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='mensagem_inscricao',
            field=models.CharField(blank=True, default='Fique ligado, as inscrições abrirão em breve.', help_text='Mensagem exibida no card de inscrições.', max_length=200, null=True),
        ),
    ]
