# Generated by Django 6.0.5 on 2026-06-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_eventocalendario_mensagem_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoCadastro',
            fields=[
            ],
            options={
                'verbose_name': '🟡 Novo Cadastro',
                'verbose_name_plural': '🟡 Novos Cadastros',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.jogador',),
        ),
    ]
