# Generated by Django 6.0.5 on 2026-06-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_novocadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='cadastro_revisado',
            field=models.BooleanField(default=False),
        ),
    ]
